# Generated by Django 4.0.2 on 2022-02-26 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_alter_ekip_creater_alter_ekip_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='equal_share',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share', to=settings.AUTH_USER_MODEL),
        ),
    ]
