# Generated by Django 4.0.2 on 2022-02-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_remove_share_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
